function [results] = calculate_seguin_metrics(similarity_matrix, network_type, dataset_name)
% Compute Seguin reliability, uniformity, identifiability
n_subj = size(similarity_matrix, 1);
intra_similarities = diag(similarity_matrix);
inter_similarities = similarity_matrix(~eye(n_subj));
reliability = mean(intra_similarities);
uniformity = mean(inter_similarities);
s_intra = std(intra_similarities);
s_inter = std(inter_similarities);
n_intra = length(intra_similarities);
n_inter = length(inter_similarities);
s_pooled = sqrt(((n_intra-1)*s_intra^2 + (n_inter-1)*s_inter^2) / (n_intra + n_inter - 2));
identifiability = (reliability - uniformity) / s_pooled;
results = struct('network_type', network_type, ...
    'dataset_name', dataset_name, ...
    'n_subjects', n_subj, ...
    'reliability', reliability, ...
    'uniformity', uniformity, ...
    'identifiability', identifiability, ...
    'reliability_std', s_intra, ...
    'uniformity_std', s_inter, ...
    'intra_similarities', intra_similarities, ...
    'inter_similarities', inter_similarities, ...
    'similarity_matrix', similarity_matrix);
end